# Note that all column names will be lowercased and all spaces in column names will be
# replaced with underscores in the resulting database table.
Stimulus:
  file_name: "CustomCurves_CustomCurves@1_ET_EventAPI_ExternDevice"
  load_columns:
    - "RowNumber"
    - "Timestamp"
    - "Temperature"
    - "Rating"

EDA:
  file_name: "Shimmer3_EDA_&_PPG_Shimmer3_EDA_&_PPG_ET_Shimmer_ShimmerDevice"
  load_columns:
    - "RowNumber"
    - "SampleNumber"
    - "Timestamp"
    - "GSR Conductance CAL"
    - "VSenseBatt CAL"
    - "Packet reception rate RAW"
  rename_columns:
    "GSR Conductance CAL": "EDA_RAW"
    "VSenseBatt CAL": "EDA_d_Battery"
    "Packet reception rate RAW": "EDA_d_PacketReceptionRate"

PPG:
  file_name: "Shimmer3_EDA_&_PPG_Shimmer3_EDA_&_PPG_ET_Shimmer_ShimmerDevice"
  load_columns:
    - "RowNumber"
    - "SampleNumber"
    - "Timestamp"
    - "Internal ADC A13 PPG CAL"
    - "Heart Rate PPG ALG"
    - "IBI PPG ALG"
    - "VSenseBatt CAL"
    - "Packet reception rate RAW"
  rename_columns:
    "Internal ADC A13 PPG CAL": "PPG_RAW"
    "Heart Rate PPG ALG": "PPG_HeartRate"
    "IBI PPG ALG": "PPG_IBI"
    "VSenseBatt CAL": "PPG_d_Battery"  # duplicate
    "Packet reception rate RAW": "PPG_d_PacketReceptionRate"  # duplicate

EEG:
  file_name: "EEG_Enobio-USB_ENOBIO-8-NE-Device_(COM3)_ET_Lsl_LslSensor"
  load_columns:
    - "RowNumber"
    - "Timestamp"
    - "Ch1"
    - "Ch2"
    - "Ch3"
    - "Ch4"
    - "Ch5"
    - "Ch6"
    - "Ch7"
    - "Ch8"
  comment: "has no SampleNumber column"

Pupil:
  file_name: "ET_Eyetracker"
  load_columns:
    - "RowNumber"
    - "Timestamp"
    - "ET_PupilLeft"
    - "ET_PupilRight"
    - "ET_DistanceLeft"
    - "ET_DistanceRight"
  rename_columns:
    "ET_PupilLeft": "Pupil_L"
    "ET_PupilRight": "Pupil_R"
    "ET_DistanceLeft": "Pupil_L_Distance"
    "ET_DistanceRight": "Pupil_R_Distance"

Face:
  file_name: "Affectiva_AFFDEX_ET_Affectiva_AffectivaCameraDevice"
  load_columns:
    - "RowNumber"
    - "SampleNumber"
    - "Timestamp"
    - "Anger"
    - "Contempt"
    - "Disgust"
    - "Fear"
    - "Joy"
    - "Sadness"
    - "Surprise"
    - "Engagement"
    - "Valence"
    - "Sentimentality"
    - "Confusion"
    - "Neutral"
    - "Attention"
    - "Brow Furrow"
    - "Brow Raise"
    - "Cheek Raise"
    - "Chin Raise"
    - "Dimpler"
    - "Eye Closure"
    - "Eye Widen"
    - "Inner Brow Raise"
    - "Jaw Drop"
    - "Lip Corner Depressor"
    - "Lip Press"
    - "Lip Pucker"
    - "Lip Stretch"
    - "Lip Suck"
    - "Lid Tighten"
    - "Mouth Open"
    - "Nose Wrinkle"
    - "Smile"
    - "Smirk"
    - "Upper Lip Raise"
    - "Blink"
    - "BlinkRate"
    - "Pitch"
    - "Yaw"
    - "Roll"
    - "Interocular Distance"
  comment: "Affectiva data is not sampled at a constant rate and can contain NaNs."

System:
  file_name: "System_Load_Monitor_iMotions.SysMonitor@1_ET_EventAPI_ExternDevice"
  load_columns:
    - "RowNumber"
    - "Timestamp"
    - "CPU Sys"
    - "Memory Sys"
    - "CPU Proc"
    - "Memory Proc"
  comment: "has no SampleNumber column"

Trials:
  file_name: "ExternalMarker_ET_EventAPI_ExternDevice"
  load_columns:
    - "Timestamp"
    - "MarkerDescription"
  comment:
    - "Metadata"
    - "MarkerDescription contains the stimulus seed and is originally send once at the start and end of each trial."